### ISSUE TITLE
buttons!

### ISSUE THREAD

**Issue by bmklein5** [weblab-class/SnappaQ#17]
editButton
delButton
team1Wins
team2Wins

**Comment by bmklein5** [comment]
just need to add API calls, consult w/ Ethan

**Comment by ewsiegel** [comment]
added the team1Wins and team2Wins calls, working on the edit and del backend

**Comment by ewsiegel** [comment]
Completed delete functionality, going to close this issue and open a new issue just for the edit button since its a little more complicated on the frontend (probably want a popup or something)
